// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/g1ave/go-cloud-disk/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/detail",
				Handler: UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/mailcodesend",
				Handler: MailCodeSendHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: FileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/user/repo/save",
					Handler: UserRepositoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/file/list",
					Handler: UserFileListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/name/update",
					Handler: FileNameUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/folder/create",
					Handler: FolderCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/delete",
					Handler: DeleteFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/move",
					Handler: MoveFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/share/create",
					Handler: FileShareCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/file/share/details/:identity",
					Handler: FileShareDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/share/save",
					Handler: FileShareSaveHandler(serverCtx),
				},
			}...,
		),
	)
}
